// Generates src/version.ts so the SDK version can be baked into the
// User-Agent at build time. Publish builds hand off the release version via
// MESA_SDK_VERSION (set by .buildkite/scripts/sdk-npm-package.mjs); all other
// builds derive it from the repo-root VERSION file.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const version =
  process.env.MESA_SDK_VERSION?.trim() ||
  fs.readFileSync(path.join(packageDir, '..', '..', '..', 'VERSION'), 'utf8').trim();

const target = path.join(packageDir, 'src', 'version.ts');
const content = `// Generated by pnpm run stamp:version. Do not edit.\nexport const SDK_VERSION = ${JSON.stringify(version)};\n`;

if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) {
  fs.writeFileSync(target, content);
}
